Feat/9 code convention
f-lab-clone/ticketing-frontend pull request #10
Opened 2023-07-23 08:04 UTC by enKODING1

#  What is this PR?
- Github Issue: #9 

# Key Changes
- npm 패키지 eslint + prettier 추가 
- devcontainer 실행 시 필요한 vscode extension 자동 설치
- convention setup파일 설정
- `npm run lint`
# Test Checklist

2023-07-23 08:49 UTC, junha-ahn requested changes

2023-07-23 08:49 UTC, junha-ahn commented on .prettierrc
> +  "semi": true,
세미 콜론 사용하지 않음으로 부탁드립니다.

tabSize: 2 도 명시해주세요

2023-07-23 10:16 UTC, junha-ahn reviewed
해당 커밋은 chore이 더 어울립니다

2023-07-23 13:32 UTC, junha-ahn commented
npm install 부분 caching 부탁 드립니다.

2023-07-23 14:24 UTC, junha-ahn commented
https://duncanleung.com/why-slow-plugin-typescript-eslint-performance-issues/

2023-07-23 14:38 UTC, junha-ahn commented
```BASH
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: eslint-plugin-jest@2[5](https://github.com/f-lab-clone/ticketing-frontend/actions/runs/5636918902/job/15269695573#step:7:6).7.0
npm WARN Found: @typescript-eslint/eslint-plugin@[6](https://github.com/f-lab-clone/ticketing-frontend/actions/runs/5636918902/job/15269695573#step:7:7).1.0
npm WARN node_modules/@typescript-eslint/eslint-plugin
npm WARN   dev @typescript-eslint/eslint-plugin@"^6.1.0" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peerOptional @typescript-eslint/eslint-plugin@"^4.0.0 || ^5.0.0" from eslint-plugin-jest@25.[7](https://github.com/f-lab-clone/ticketing-frontend/actions/runs/5636918902/job/15269695573#step:7:8).0
npm WARN node_modules/eslint-plugin-jest
npm WARN   eslint-plugin-jest@"^25.3.0" from eslint-config-react-app@7.0.1
npm WARN   node_modules/eslint-config-react-app
npm WARN 
npm WARN Conflicting peer dependency: @typescript-eslint/eslint-plugin@5.62.0
npm WARN node_modules/@typescript-eslint/eslint-plugin
npm WARN   peerOptional @typescript-eslint/eslint-plugin@"^4.0.0 || ^5.0.0" from eslint-plugin-jest@25.7.0
npm WARN   node_modules/eslint-plugin-jest
npm WARN     eslint-plugin-jest@"^25.3.0" from eslint-config-react-app@7.0.1
npm WARN     node_modules/eslint-config-react-app
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated stable@0.1.[8](https://github.com/f-lab-clone/ticketing-frontend/actions/runs/5636918902/job/15269695573#step:7:9): Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated workbox-cacheable-response@6.6.0: workbox-background-sync@6.6.0
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3[14](https://github.com/f-lab-clone/ticketing-frontend/actions/runs/5636918902/job/15269695573#step:7:15)2
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
```

npm install시 나오는 해당 에러에 대해 설명 부탁드립니다.

2023-07-23 16:33 UTC, enKODING1 commented
# 패키지 설치 중 `Error` 발생한 이유 
 
`node` :  v18
`node-sass` : v7.0.3

[node-sass](https://www.npmjs.com/package/node-sass)
![node](https://github.com/f-lab-clone/ticketing-frontend/assets/65354945/7f4f540e-30f0-4738-8468-49b596c0a91d)

현재 최신버전인 9.0.0 설치로 해결

2023-07-24 02:51 UTC, junha-ahn requested changes

2023-07-24 02:51 UTC, junha-ahn commented on .github/workflows/lint.yml
> +        if: steps.cache_dependencies.outputs.cache-hit == ''
해당 줄 무슨 의미인가요? 조금더 이해하기 쉽게 변경해주세요.

2023-07-24 02:51 UTC, junha-ahn commented on .github/workflows/lint.yml
> +          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
각 env들을 어떻게 활용하는지 간단하게 설명 부탁드립니다

2023-07-24 02:57 UTC, junha-ahn commented on .github/workflows/lint.yml
> +          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
혹시 해당 링크에 있는 캐싱으로는 불가능한지도 테스트 부탁드려요

https://github.com/actions/setup-node#caching-global-packages-data

2023-07-24 16:36 UTC, junha-ahn commented
Actually the setup-node action does not cache node_modules. It caches [global cache directory](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies).

from https://github.com/actions/setup-node/issues/416

2023-07-24 16:50 UTC, merged